modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="mildly_interesting_biomes"
version="1.0.0"
displayName="Mildly Interesting Biomes"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="mrcnew, MCreator"

[[dependencies.mildly_interesting_biomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




